version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    networks:
      - default
    environment:
      - POSTGRES_USER=shu
      - POSTGRES_PASSWORD=shu
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE="postgresql://shu:shu@postgres12:5432/simple_bank?sslmode=disable"
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres12:5432","--timeout=30", "--", "/app/start.sh" ]
    command: [ "/app/main" ]

networks:
  default:
    driver: bridge